CREATE TABLE ACCOUNT (
    ID INT PRIMARY KEY, 
    Username VARCHAR(20) NOT NULL,
    Password VARCHAR(20) NOT NULL
);

CREATE TABLE USER (
    ID INT PRIMARY KEY, 
    NOM VARCHAR(20) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    GSM VARCHAR(20),
    ACCOUNT_ID INT,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);